## Объектно-ориентированное программирование и информационная безопасность

*Валерий Семенов, Самарский университет*

<h1 style="text-align:center; margin-top:60px">Библиотека NumPy</h1>

<div style="text-align:center"><img src="numpy.png"></div>

<div style="text-indent:30px; text-align:justify"><a href="https://numpy.org"><strong>NumPy</strong></a> (<strong>Num</strong>erical <strong>Py</strong>thon) – одна из самых популярных библиотек для инженерных и научных вычислений в Python, она содержит множество методов для работы с многомерными массивами и отличается высокой скоростью обработки больших объемов данных. </div>
    
<div style="text-indent:30px; text-align:justify; margin-top:20px">Мощная функциональность этой библиотеки используется в нескольких других популярных библиотеках – Pandas, SciPy, Matplotlib, Scikit-learn и TensorFlow. </div>

<div style="text-indent:30px; text-align:justify; margin-top:20px">Про историю создания этой библиотеки можно почитать, например, <a href="https://ru.wikipedia.org/wiki/NumPy"><strong>здесь</strong></a>. </div>


<h2 style="text-align:center; margin-top:20px">Зачем нужен NumPy</h2>

<div style="text-indent:30px; text-align:justify">Необходимость в специальной библиотеке для работы с большими массивами чисел возникает из-за скорости работы Python, поскольку он печально известен своей медлительностью. Программы, написанные на таких языках, как C#, C++, Node.js, Go и многих других, могут выполняться в 30-40 раз быстрее, чем эквивалентные программы Python. Причин несколько, включая тот факт, что Python является интерпретируемым языком (код должен быть скомпилирован во время выполнения), имеет динамическую типизацию и работает в одном потоке. </div>

<div style="text-indent:30px; text-align:justify; margin-top:20px">Библиотека NumPy частично написана на Python, а частично на C/C++ и Fortran — в тех местах, которые требуют скорости. Кроме того, код NumPy оптимизирован под большинство современных процессоров. </div>


<h2 style="text-align:center; margin-top:20px">Где используется NumPy</h2>

<div style="text-indent:30px; text-align:justify">NumPy используется везде, где нужна быстрая обработка больших массивов данных: </div>

<div style=" margin-left:50px">
<li style="text-align:justify">Инженерные и научные вычисления в области физики, математики, биологии, химии и т.д. </li>
<li style="text-align:justify">Обработка изображений и звука – изменение размера, применение фильтров, сжатие и т.п. </li>
<li style="text-align:justify">Машинное обучение, искусственный интеллект и Data Science – обработка и статистический анализ данных. </li>
<li style="text-align:justify">Компьютерное зрение – распознавание образов и сегментация изображений. </li>
<li style="text-align:justify">Финансовые вычисления – расчет доходности активов и инвестиций, риск-менеджмент, оценка дисконтированной стоимости и т.д. </li>
<li style="text-align:justify">Геофизические и геологические исследования – обработка геоданных и анализ графиков. </li>
</div>

<h2 style="text-align:center; margin-top:20px">Установка NumPy</h2>

<div style="text-indent:30px; text-align:justify">В Anaconda пакет NumPy установлен по умолчанию. Поэтому нет необходимости устанавливать его через менеджер пакетов. </div>

<div style="text-indent:30px; text-align:justify">Для использования NumPy в программе, необходимо его импортировать. </div>

In [1]:
import numpy as np

<div style="text-indent:30px; text-align:justify">Библиотека NumPy используется настолько часто и настолько многими, что сложилась традиция импортировать <strong>NumPy</strong> с псевдонимом <strong>np</strong>. </div>

<h2 style="text-align:center; margin-top:20px">Понятие массива Numpy</h2>

<div style="text-indent:30px; text-align:justify">Основным объектом NumPy является однородный многомерный <strong>массив</strong> данных (тип <strong>ndarray</strong>, сокращение от <i>n-dimensional array</i>, n-мерный массив). </div>
    
<div style="text-indent:30px; text-align:justify">Это многомерный массив элементов (обычно чисел), одного типа (либо только целые числа, либо числа с плавающей точкой, либо строки, либо булевы (логические) значения). </div>
    
<div style="text-indent:30px; text-align:justify; margin-top:20px">Чем же удобны массивы? </div>
    
<div style="text-indent:30px; text-align:justify">Во-первых, они используют меньше памяти и работают быстрее, чем обычные списки Python. </div>
 
<div style="text-indent:30px; text-align:justify">Во-вторых, с ними очень удобно работать. Все операции над массивами будут производиться поэлементно, то есть, для выполнения действий над каждым элементом массива, нам не придется использовать какие-то специальные конструкции вроде циклов, мы сможем обращаться сразу ко всему массиву. </div>

<div style="text-indent:200px; text-align:justify; margin-top:20px"><u>Примеры одномерного, двухмерного и трехмерного массивов:</u></div>

<div style="text-align:center"><img src="ndarray.jpg" width="800"></div>

<h2 style="text-align:center; margin-top:40px">Характеристики (атрибуты) массива</h2>

<div style="text-indent:30px; text-align:justify">Теперь познакомимся с характеристиками самого массива. Создадим массив <strong>M</strong> и будем с ним работать: </div>

In [2]:
M = np.array([[5.2, 3.0, 4.5], 
              [9.1, 0.1, 0.3]])
M

array([[5.2, 3. , 4.5],
       [9.1, 0.1, 0.3]])

<div style="text-indent:30px; text-align:justify; margin-top:20px">Массивы бывают многомерными, значит, у массива есть число измерений. Давайте его найдем: </div>

In [3]:
M.ndim    # Сокращение от dimensions (размеры)

2

<div style="text-indent:30px; text-align:justify">Действительно, всего два измерения - чтобы указать на число <strong>4.5</strong> из этого массива, нам понадобятся всего две координаты – номер строки (<strong>0</strong>) и номер столбца (<strong>2</strong>). </div>

In [4]:
M[0,2]

4.5

<div style="text-indent:30px; text-align:justify; margin-top:20px">Теперь посмотрим на форму или вид массива (shape): </div>

In [5]:
M.shape  # shape (форма) = 2 строки и 3 столбца

(2, 3)

<div style="text-indent:30px; text-align:justify; margin-top:20px">Кроме того, можем найти общее число элементов в массиве, то есть, размер (size): </div>

In [6]:
M.size  # Всего 6 элементов

6

<h2 style="text-align:center; margin-top:20px">Создание массивов</h2>

<h3 style="text-align:center; margin-top:40px">Функция <strong>np.array()</strong></h3>

<div style="text-indent:30px; text-align:justify">Во-первых, массив можно создать с помощью функции <strong>np.array()</strong>, которой мы передаем, например, список или кортеж элементов: </div>

In [7]:
# Создадим одномерный массив из списка
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# Создадим одномерный массив из кортежа
arr = np.array((0, 1, 2, 3, 4, 5, 6, 7, 8, 9))
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.array([3.14, 4, 2, 3]) # Если типы элементов не совпадают, NumPy попытается выполнить повышающее приведение типов

array([3.14, 4.  , 2.  , 3.  ])

<h3 style="text-align:center; margin-top:20px">Функция <strong>np.arange()</strong></h3>

<div style="text-indent:30px; text-align:justify">Кроме того, можно воспользоваться функцией <strong>np.arange()</strong>. Эта функция, как и функция <strong>range()</strong>, с которой мы уже знакомы, создает линейную последовательность элементов. Обязательным параметром является верхняя граница, которая не входит в последовательность. </div>

In [10]:
# Создадим одномерный массив из 10 элементов
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

<div style="text-indent:30px; text-align:justify">Нижняя граница и шаг обязательными не являются: </div>

In [11]:
# Создаем массив, заполненный линейной последовательностью, 
# начинающейся с 3 и заканчивающейся 20, с шагом 2 (аналогично встроенной функции range())
arr = np.arange(3, 20, 2)
print(arr)

[ 3  5  7  9 11 13 15 17 19]


In [12]:
type(arr)

numpy.ndarray

<div style="text-indent:30px; text-align:justify">Отличие <strong>range()</strong> от функции <strong>np.arange()</strong> заключается в том, что первая не допускает использования типа <strong>float</strong>. </div>

<div style="text-indent:30px; text-align:justify; margin-top:20px">Попробуем создать список с помощью функций <strong>range()</strong> и <strong>list()</strong> и получим ошибку: </div>

In [13]:
list(range(2, 5.5, 0.5))

TypeError: 'float' object cannot be interpreted as an integer

<div style="text-indent:30px; text-align:justify">При этом в массиве NumPy тип <strong>float</strong> вполне может использоваться: </div>

In [14]:
np.arange(2, 5.5, 0.5)

array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

<h3 style="text-align:center; margin-top:20px">Функция <strong>np.linspace()</strong></h3>

<div style="text-indent:30px; text-align:justify">Эта функция создает линейную последовательность элементов, равномерно располагающихся в заданном интервале. Она работает как функция <strong>np.arange()</strong>. Но вместо указания размера шага она определяет количество элементов в интервале между начальным и конечным значениями: </div>

In [15]:
# Создаем массив из 15 значений, равномерно располагающихся между -5.5 и 2.3
np.linspace(-5.5, 2.3, 15)

array([-5.5       , -4.94285714, -4.38571429, -3.82857143, -3.27142857,
       -2.71428571, -2.15714286, -1.6       , -1.04285714, -0.48571429,
        0.07142857,  0.62857143,  1.18571429,  1.74285714,  2.3       ])

<div style="text-indent:30px; text-align:justify">Также библиотека numpy позволяет создать массивы, состоящие из одних нулей или единиц, одинаковых значений, а также  «пустые» массивы (на практике используются редко). Удобство заключается в том, что сначала можно создать массив, инициализировать его (например, заполнить нулями), а затем заменить нули на другие значения в соответствии с требуемыми условиями. </div>

<h3 style="text-align:center; margin-top:20px">Функция <strong>np.zeros()</strong></h3>

<div style="text-indent:30px; text-align:justify; margin-top:20px">Создадим двумерный массив из одних нулей в виде значений с плавающей точкой (по умолчанию): </div>

In [16]:
Z = np.zeros((3, 5))   # Размеры задаются в виде кортежа - не теряйте еще одни круглые скобки
Z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

<div style="text-indent:30px; text-align:justify; margin-top:20px">Теперь создадим трехмерный массив из одних нулей в виде целых значений: </div>

In [17]:
Z = np.zeros((3, 4, 2), dtype=int)   # Размеры задаются в виде кортежа
Z

array([[[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]]])

<h3 style="text-align:center; margin-top:20px">Функция <strong>np.ones()</strong></h3>

<div style="text-indent:30px; text-align:justify; margin-top:20px">Пример создания двумерного массива из единиц в виде целых значений: </div>

In [18]:
m = np.ones((3, 5), dtype=int)
m

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

<div style="text-indent:30px; text-align:justify; margin-top:20px">Пример создания двумерного массива из логического типа данных (все элементы массива равны True): </div>

In [19]:
m = np.ones((3, 5), dtype=bool)
m

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

<h3 style="text-align:center; margin-top:20px">Функция <strong>np.eye()</strong></h3>

<div style="text-indent:30px; text-align:justify; margin-top:20px">А вот так выглядит единичная матрица – таблица из 0 и 1, в которой число строк и столбцов одинаково, и где на главной диагонали стоят 1: </div>

In [20]:
E = np.eye((5))
E

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

<div style="text-indent:30px; text-align:justify; margin-top:20px">Несмотря на то, что для создания единичной матрицы есть специальный метод, давайте посмотрим, как бы мы создавали ее «вручную» (мы мало работали со вложенными циклами, поэтому стоит повторить). </div>

<div style="text-indent:30px; text-align:justify; margin-top:20px">Для этого нам потребовались бы вложенные циклы: </div>

In [21]:
I = np.zeros((4, 4))

for i in range(0, I.shape[0]):
    for j in range(0, I.shape[1]):
        if i == j:
            I[i][j] = 1
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

<div style="text-indent:30px; text-align:justify">Данный пример заодно показывает одну важную особенность — массивы, как и списки, являются изменяемыми объектами в Python. </div>

<h3 style="text-align:center; margin-top:20px">Функция <strong>np.full()</strong></h3>

<div style="text-indent:30px; text-align:justify; margin-top:20px">Пример создания двумерного массива, заполненного значением <strong>3.14</strong>: </div>

In [22]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

<h2 style="text-align:center; margin-top:40px">Создание массивов со случайными элементами</h2>

<div style="text-indent:30px; text-align:justify; margin-top:40px">Для создания массивов со случайными элементами служит модуль <strong>numpy.random</strong>. </div>

<h3 style="text-align:center; margin-top:40px">Функция <strong>np.random.sample()</strong></h3>

<div style="text-indent:30px; text-align:justify; margin-top:20px">Самый простой способ задать массив со случайными элементами - использовать функцию <strong>sample</strong> (или <strong>random</strong>, или <strong>random_sample</strong>, или <strong>ranf</strong> - это все одна и та же функция): </div>

In [23]:
# Создаем массив размером 3 x 5 равномерно распределенных случайных значений в диапазоне [0, 1]
# np.random.random((3, 5))
# np.random.random_sample((3, 5))
# np.random.ranf((3, 5))

np.random.sample((3, 5))

array([[0.97271746, 0.47340792, 0.486786  , 0.05483375, 0.62849926],
       [0.6283741 , 0.66525056, 0.0136125 , 0.26279421, 0.92801512],
       [0.93906615, 0.42229848, 0.46289972, 0.62001445, 0.36350522]])

<div style="text-indent:30px; text-align:justify">Функция без аргументов возвращает просто одно число, с одним целым числом - одномерный массив, с кортежем - массив с размерами, указанными в кортеже (все числа - из промежутка [0, 1]). </div>

<div style="text-indent:30px; text-align:justify; margin-top:20px">С помощью функции <strong>randint()</strong> можно создать массив из целых чисел. </div>
    
<div style="text-indent:30px; text-align:justify">Для вызова функции удобно использовать именованные аргументы, вместо позиционных: </div>
    
<div style=" margin-left:50px">
<li style="text-align:justify"><strong>low</strong> - начальное значение;</li>
<li style="text-align:justify"><strong>high</strong> - конечное значение (функция <strong>randint()</strong> не включает в себя это число);</li>
<li style="text-align:justify"><strong>size</strong> - размеры возвращаемого массива (кортеж).</li>
</div>

In [24]:
# np.random.randint(-2, 5, (4,5))
np.random.randint(low=-2, high=5, size=(4,5))  # Удобнее использовать именованные аргументы, вместо позиционных

array([[-2,  1,  4,  2,  2],
       [ 1,  4, -2,  3,  3],
       [ 1,  0, -1, -2,  2],
       [ 4, -2, -1,  4,  1]])

<div style="text-indent:30px; text-align:justify; margin-top:20px">В предыдущих примерах мы генерировали числа из непрерывного <a href="https://ru.wikipedia.org/wiki/%D0%94%D0%B8%D1%81%D0%BA%D1%80%D0%B5%D1%82%D0%BD%D0%BE%D0%B5_%D1%80%D0%B0%D0%B2%D0%BD%D0%BE%D0%BC%D0%B5%D1%80%D0%BD%D0%BE%D0%B5_%D1%80%D0%B0%D1%81%D0%BF%D1%80%D0%B5%D0%B4%D0%B5%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5"><strong>равномерного распределения</strong></a>. </div>

<div style="text-indent:30px; text-align:justify; margin-top:20px">NumPy также включает генераторы для других распределений, таких как: Бета, биномиальное, хи-квадрат, Дирихле, экспоненциальное, Фишера, Гамма, геометрическое, Гамбала, гипергеометрическое, Лапласа, логистическое, логнормальное, логарифмическое, мультиномиальное, многомерное нормальное, отрицательное биномиальное, нецентральное хи-квадрат, нецентральное Фишера, нормальное (Гаусса), Парето, Пуассона, степенное, Рэлея, Коши, Стьюдента, треугольное, Фон-Миса, Вальда, Вейбулла и Ципфа. </div>

<h3 style="text-align:center; margin-top:40px">Функция <strong>np.random.normal()</strong></h3>
    
<div style="text-indent:30px; text-align:justify; margin-top:20px"><a href="https://ru.wikipedia.org/wiki/%D0%9D%D0%BE%D1%80%D0%BC%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D0%B5_%D1%80%D0%B0%D1%81%D0%BF%D1%80%D0%B5%D0%B4%D0%B5%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5"><strong>Нормальное распределение</strong></a> (также называемое распределением Гаусса или Гаусса — Лапласа), занимает одно из центральных мест в статистике и машинном обучении. Оно характеризуется симметричной «колоколообразной» кривой, которая имеет огромное значение в теории вероятностей и анализа данных. </div>

<div style="text-indent:30px; text-align:justify; margin-top:20px">Функция <strong>np.random.normal()</strong> создает массив с нормально распределенными элементами. </div>

<div style="text-indent:30px; text-align:justify">Для вызова функции удобно использовать именованные аргументы, вместо позиционных: </div>
    
<div style=" margin-left:50px">
<li style="text-align:justify"><strong>loc</strong> - математическое ожидание (среднее значение) распределения (<strong>μ</strong>);</li>
<li style="text-align:justify"><strong>scale</strong> - стандартное отклонение (<strong>σ</strong>)</li>
<li style="text-align:justify"><strong>size</strong> - размеры возвращаемого массива (кортеж).</li>
</div>

<div style="text-indent:30px; text-align:justify; margin-top:20px">Пример генерации чисел из нормального распределения (Гаусса) при среднем значении <strong>μ = 1.5</strong> и стандартном отклонении <strong>σ = 4.0</strong>: </div>

In [25]:
np.random.normal(loc=1.5, scale=4, size=25)

array([11.96981497,  4.80944659,  6.56125972,  1.48002467,  3.0198823 ,
       -1.63332516, -0.2082319 , -0.11560365,  1.61295695, -0.23749819,
        3.44470336,  4.57409383, -0.98457806,  2.12112966,  8.68653596,
        6.31103815, 10.12247785,  2.20683484,  2.82335713,  4.57881697,
       -1.99001152,  1.22293726,  3.88875255,  5.30633798, -2.48067463])

<div style="text-indent:30px; text-align:justify; margin-top:20px">Стандартным нормальным распределением называется нормальное распределение с математическим ожиданием <strong>μ = 0</strong> и стандартным отклонением <strong>σ = 1</strong>: </div>

In [26]:
np.random.normal(size=15)

array([-0.28751133, -0.31481052, -0.54276728,  0.66250318, -1.23594968,
       -1.03862532,  2.29670889, -2.0448765 ,  0.54758251,  1.32044122,
       -1.40199375, -0.8796905 ,  0.4968837 ,  0.13589905,  0.03376497])

<h3 style="text-align:center; margin-top:40px">Выбор и перемешивание</strong></h3>

<div style="text-indent:30px; text-align:justify; margin-top:20px">Перемешать массив можно с помощью функции <strong>shuffle()</strong>: </div>

In [27]:
a = np.random.randint(low=-25, high=50, size=(4,5))  # Создаем двумерный массив из целых чисел [-25,50]
a

array([[-15,  33,   5,   7, -25],
       [ 39, -10,  -4,  37,  49],
       [ -9, -16,  19,  49,  43],
       [-23,  12,  41, -19,   3]])

In [28]:
np.random.shuffle(a)  # Перемешиваем массив
a

array([[-15,  33,   5,   7, -25],
       [-23,  12,  41, -19,   3],
       [ 39, -10,  -4,  37,  49],
       [ -9, -16,  19,  49,  43]])

<h3 style="text-align:center; margin-top:40px">Функция <strong>np.random.seed()</strong></h3>

<div style="text-indent:30px; text-align:justify; margin-top:20px">В Python, как и в любом другом языке, используется так называемый <a href="https://ru.wikipedia.org/wiki/%D0%93%D0%B5%D0%BD%D0%B5%D1%80%D0%B0%D1%82%D0%BE%D1%80_%D0%BF%D1%81%D0%B5%D0%B2%D0%B4%D0%BE%D1%81%D0%BB%D1%83%D1%87%D0%B0%D0%B9%D0%BD%D1%8B%D1%85_%D1%87%D0%B8%D1%81%D0%B5%D0%BB"><strong>генератор псевдослучайных чисел</strong></a>. Таким образом любая функция для генерации случайного числа выдает не случайное число, а число которое вычисляется алгоритмом на основе другого числа (по умолчанию это текущее время). </div>
    
<div style="text-indent:30px; text-align:justify; margin-top:20px">Функция <strong>np.random.seed()</strong> позволяет изменить начальное число, которое используется для генерации случайного числа, а так как "случайные" числа выдаются одним и тем же алгоритмом, то при одинаковом параметре в <strong>np.random.seed()</strong>, будут и одинаковые "случайные" числа (инициализация генератора случайных чисел). </div>

<h2 style="text-align:center; margin-top:40px">Индексация массивов</h2>

In [29]:
np.random.seed(0) # Начальное значение для целей воспроизводимости
x1 = np.random.randint(10, size=6)         # Одномерный массив
x2 = np.random.randint(20, size=(3, 4))    # Двумерный массив

print("Одномерный массив: \n", x1)
print("\n Двумерный массив: \n", x2)

Одномерный массив: 
 [5 0 3 3 7 9]

 Двумерный массив: 
 [[19 18  4  6]
 [12  1  6  7]
 [14 17  5 13]]


In [30]:
x1   # Весь одномерный массив x1

array([5, 0, 3, 3, 7, 9])

In [31]:
x1[0]  # Элемент одномерного массива x1 с индексом (номером) 0

5

In [32]:
x1[2]  # Элемент одномерного массива x1 с индексом (номером) 2

3

In [33]:
x1[-1]  # ПОСЛЕДНИЙ элемент одномерного массива x1

9

In [34]:
x2  # Весь двумерный массив x2

array([[19, 18,  4,  6],
       [12,  1,  6,  7],
       [14, 17,  5, 13]])

In [35]:
x2[1][-1]  # Элемент двумерного массива x2, находящийся на пересечении 1-ой строки и ПОСЛЕДНЕГО столбца

7

<div style="text-indent:30px; text-align:justify; margin-top:20px">Обращаться к элементам в многомерном массиве можно с помощью разделенных запятыми кортежей индексов: </div>

In [36]:
x2[1,-1]  # Элемент двумерного массива x2, находящийся на пересечении 1-ой строки и ПОСЛЕДНЕГО столбца

7

<div style="text-indent:30px; text-align:justify; margin-top:20px">Мы можем изменить значение любого элемента массива, используя любую из перечисленных выше индексных нотаций: </div>

In [37]:
x2

array([[19, 18,  4,  6],
       [12,  1,  6,  7],
       [14, 17,  5, 13]])

In [38]:
x2[1, 2] = 666
x2

array([[ 19,  18,   4,   6],
       [ 12,   1, 666,   7],
       [ 14,  17,   5,  13]])

In [39]:
x2[-1][-1] = 97.91

In [40]:
x2 # Числа после точки были отброшены!

array([[ 19,  18,   4,   6],
       [ 12,   1, 666,   7],
       [ 14,  17,   5,  97]])

<h3 style="text-align:center; margin-top:40px">Срезы массивов (доступ к подмассивам)</h3>

<div style="text-indent:30px; text-align:justify; margin-top:20px">Аналогично доступу к отдельным элементам массива можно использовать квадратные скобки для доступа к подмассивам с помощью срезов (slicing), обозначаемых знаком двоеточия (<strong>:</strong>). </div>
    
<div style="text-indent:30px; text-align:justify">Синтаксис срезов библиотеки NumPy соответствует аналогичному синтаксису для стандартных списков языка Python. Для доступа к срезу массива <strong>x</strong> используйте следующий синтаксис: &nbsp;&nbsp; <strong>x[начало:конец:шаг]</strong></div>

<div style="text-indent:30px; text-align:justify; margin-top:10px">Если какие-либо из этих значений не указаны, значения применяются по умолчанию (начало = 0, конец = размер соответствующего измерения, шаг = 1). </div>

<div style="text-indent:30px; text-align:justify; margin-top:10px">Примеры: </div>

In [41]:
x1  # Весь одномерный массив x1

array([5, 0, 3, 3, 7, 9])

In [42]:
print(x1[:4])
print(x1[4:])
print(x1[-3:-1])
print(x1[::2])

[5 0 3 3]
[7 9]
[3 7]
[5 3 7]


In [43]:
x2  # Весь двумерный массив x2

array([[ 19,  18,   4,   6],
       [ 12,   1, 666,   7],
       [ 14,  17,   5,  97]])

In [44]:
print(x2[:2])

[[ 19  18   4   6]
 [ 12   1 666   7]]


<div style="text-indent:30px; text-align:justify">Многомерные срезы задаются схожим образом, с разделением срезов запятыми: </div>

In [45]:
x2[:2, :3] # две строки, три столбца

array([[ 19,  18,   4],
       [ 12,   1, 666]])

In [46]:
x2[:, 1:] # Все строки и три последних столбца

array([[ 18,   4,   6],
       [  1, 666,   7],
       [ 17,   5,  97]])

In [47]:
# Измерения подмассивов также можно «переворачивать»:
x2[::-1, ::-1]

array([[ 97,   5,  17,  14],
       [  7, 666,   1,  12],
       [  6,   4,  18,  19]])

<h3 style="text-align:center; margin-top:40px">Изменение формы массивов</h3>
    
<div style="text-indent:30px; text-align:justify; margin-top:20px">Еще одна удобная операция — изменение формы массивов методом <strong>reshape()</strong>. </div>
    
<div style="text-indent:30px; text-align:justify; margin-top:20px">Например, если вам требуется поместить числа от <strong>1</strong> до <strong>9</strong> в таблицу <strong>3×3</strong>, сделать это можно следующим образом: </div>

In [48]:
grid = np.arange(1, 10)  # Создаем одномерный массив из 9 чисел
grid

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
grid = np.arange(1, 10).reshape((3, 3))  # Преобразуем его в матрицу 3x3
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

<div style="text-indent:30px; text-align:justify">Обратите внимание, что размер исходного массива должен соответствовать размеру измененного. </div>

<h3 style="text-align:center; margin-top:40px">"Прихотливая" индексация</h3>

<div style="text-indent:30px; text-align:justify; margin-top:20px">«Прихотливая» индексация (fancy indexing) похожа на уже рассмотренную нами простую индексацию, но вместо скалярных значений передаются массивы индексов. Это дает возможность очень быстрого доступа и модификации сложных подмножеств значений массива. </div>

<div style="text-indent:30px; text-align:justify; margin-top:20px">Суть «прихотливой» индексации  проста - она заключается в передаче массива индексов с целью одновременного доступа к нескольким элементам массива. </div>

<div style="text-indent:30px; text-align:justify; margin-top:20px">Рассмотрим пример: </div>

In [50]:
x = np.random.randint(100, size=10)  # Создадим массив из 10 чисел
x

array([72,  9, 20, 80, 69, 79, 47, 64, 82, 99])

<div style="text-indent:30px; text-align:justify">Допустим, нам требуется обратиться к трем различным элементам. </div>
    
<div style="text-indent:30px; text-align:justify">Можно сделать это следующим образом: </div>

In [51]:
x[3], x[7], x[2]   # Пусть нам требуются три элемента массива в указанном порядке

(80, 64, 20)

<div style="text-indent:30px; text-align:justify; margin-top:20px">С другой стороны, можно передать единый список индексов и получить тот же результат: </div>

In [52]:
ind = [3, 7, 2]   # Создадим список с нужными номерами
x[ind]            # Передадим его в качестве

array([80, 64, 20])

<div style="text-indent:30px; text-align:justify">В случае «прихотливой» индексации форма результата отражает форму массивов индексов (index arrays), а не форму индексируемого массива. </div>

In [53]:
ind = np.array([[3, 7],[4, 2]])  # Создадим двумерный массив индексов
ind

array([[3, 7],
       [4, 2]])

In [54]:
x[np.array(ind)]  # Извлечем из одномерного исходного массива элементы в соответствии с формой массива ind

array([[80, 64],
       [69, 20]])

<h3 style="text-align:center; margin-top:40px">Слияние и разбиение массивов</h3>

<div style="text-indent:30px; text-align:justify">Слияние, или объединение, двух массивов в библиотеке NumPy выполняется в основном с помощью методов <strong>np.concatenate</strong>, <strong>np.vstack</strong> и <strong>np.hstack</strong>. Метод <strong>np.concatenate</strong> принимает на входе кортеж или список массивов в качестве первого аргумента: </div>

In [55]:
x = np.array([1, 3, 5])  # Одномерный массив x
y = np.array([7, 9, 11]) # Одномерный массив y
np.concatenate([x, y])   # Слияние двух массивов

array([ 1,  3,  5,  7,  9, 11])

<div style="text-indent:30px; text-align:justify">Мы можем использовать знак плюс, для случае слияния списков: </div>

In [56]:
a = [1, 3, 5]   # Список a
b = [7, 9, 11]  # Список b
a + b           # Слияние двух списков

[1, 3, 5, 7, 9, 11]

<div style="text-indent:30px; text-align:justify">А вот при использовании знака плюс для массивов, мы получим поэлементное сложение элементов массивов (и только в случае одинаковой длины массивов): </div>

In [57]:
x + y  # Поэлементное сложение двух массивов

array([ 8, 12, 16])

<div style="text-indent:30px; text-align:justify">Можно объединять более двух массивов одновременно: </div>

In [58]:
z = [99, 88, 77]
print(np.concatenate([x, y, z])) # Слияние трех массивов

[ 1  3  5  7  9 11 99 88 77]


<div style="text-indent:30px; text-align:justify; margin-top:20px">Для объединения двумерных массивов можно также использовать <strong>np.concatenate</strong>: </div>

In [59]:
grid = np.array([[1, 2, 3], 
                 [4, 5, 6]])

In [60]:
# Слияние по первой оси координат (с индексом 0)
# np.concatenate([grid, grid], axis=0)
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [61]:
# Слияние по второй оси координат (с индексом 1)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

<div style="text-indent:30px; text-align:justify; margin-top:20px">Для работы с массивами с различающимися измерениями удобнее и понятнее использовать функции <strong>np.vstack</strong> (вертикальное объединение) и <strong>np.hstack</strong> (горизонтальное объединение): </div>

In [62]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7], [6, 5, 4]])

# Объединяет массивы по вертикали
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [63]:
y = np.array([[99],[55]])

# Объединяет массивы по горизонтали
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 55]])

<div style="text-indent:30px; text-align:justify; margin-top:20px">Противоположностью слияния является разбиение, выполняемое с помощью функций <strong>np.split</strong>, <strong>np.hsplit</strong> и <strong>np.vsplit</strong>. </div>

<div style="text-indent:30px; text-align:justify">Каждой из них необходимо передавать список индексов, задающих точки в которых происходит разбиение: </div>

In [64]:
x = [1, 2, 3, 99, 77, 55, 34, 3, 2, 1, 0, -2]  # Одномерный массив x
x1, x2, x3, x4 = np.split(x, [3, 7, 10])       # Разрезаем массив в трех точках на четыре подмассива
print(x1, x2, x3, x4)

[1 2 3] [99 77 55 34] [3 2 1] [ 0 -2]


<div style="text-indent:30px; text-align:justify; margin-top:20px">Соответствующие функции <strong>np.hsplit</strong> и <strong>np.vsplit</strong> действуют аналогично: </div>

In [65]:
grid = np.arange(16).reshape((4, 4))  # Массив grid 4x4
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [66]:
upper, lower = np.vsplit(grid, [2])  # Второй массив начнется со строки, имеющей индекс 2 в исходном массиве
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [67]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


<h2 style="text-align:center">Арифметические функции</h2>
<div style="text-align:center"><img src="arithmetic.png" width="600"></div>

In [68]:
x = np.arange(4)
print("x =", x)
print("x + 5 =", x + 5)   # Прибавляем к каждому элементу массива число 5, это то же самое, что = np.add(x,5)
print("x - 5 =", x - 5)   # Вычитаем  из каждого элемента массива число 5, это то же самое, что = np.subtract(x,5)
print("x * 2 =", x * 2)   # Умножаем каждый элемент массива на число 2, это то же самое, что = np.multiply(x,2)
print("x / 2 =", x / 2)   # Делим каждый элемент массива на число 2, это то же самое, что = np.divide(x,2)
print("x // 2 =", x // 2) # Делим каждый элемент массива на число 2 с округлением в меньшую сторону, это то же самое, что = np.floor_divide(x,2)

x = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [69]:
print("-x = ", -x)         # Меняем знак каждого элемента массива на противоположный
print("x ** 2 = ", x ** 2) # Возводим каждый элемент массива в степень
print("x % 2 = ", x % 2)   # Вычисляем остаток от деления каждого элемента массива

-x =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2 =  [0 1 0 1]


In [70]:
-(0.5*x + 1) ** 2  # Вычисляем выражение для каждого элемента массива

array([-1.  , -2.25, -4.  , -6.25])

In [71]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)     # Встроенная функция для вычисления абсолютного значения каждого элемента массива

array([2, 1, 0, 1, 2])

In [72]:
np.abs(x)  # Функция ИЗ NUMPY для вычисления абсолютного значения каждого элемента массива

array([2, 1, 0, 1, 2])

<h2 style="text-align:center; margin-top:40px; margin-bottom:30px">Агрегирование (минимум, максимум и все, что посередине)</h2>

<div style="text-align:center"><img src="aggregation.png" width="600"></div>

In [73]:
big_array = np.random.rand(1000000)   # Создадим большой одномерный массив

In [74]:
np.sum(big_array)   # Сумма всех элементов массива, это то же самое, что = big_array.sum()

500385.13121223805

In [75]:
big_array.sum()     # Сумма всех элементов массива с использованием метода sum()

500385.13121223805

In [76]:
sum(big_array)      # Встроенная функция sum()

500385.1312122504

In [77]:
np.max(big_array)   # Максимальное значение всех элементов массива

0.9999997207656334

In [78]:
big_array.max()     # Максимальное значение всех элементов массива с использованием метода max()

0.9999997207656334

In [79]:
max(big_array)      # Встроенная функция max()

0.9999997207656334

In [80]:
np.mean(big_array)  # Среднее значение всех элементов массива

0.500385131212238

In [81]:
big_array.mean()    # Среднее значение всех элементов массива с использованием метода mean()

0.500385131212238

In [82]:
mean(big_array)     # А вот такой встроенной функции нет

NameError: name 'mean' is not defined

In [83]:
arr = np.array([1, 2, np.nan, 1])
arr

array([ 1.,  2., nan,  1.])

In [84]:
np.nanmean(arr)   # Среднее значение всех элементов массива с NaN-безопасной функцией mean()

1.3333333333333333

In [85]:
np.mean(arr)   # Среднее значение всех элементов массива с обычной функцией mean()
# Функция не работает, потому что есть элементы массива не содержащие число.

nan

In [86]:
M = np.random.random((3, 4))  # Двумерный массив
print(M)

[[0.20020551 0.71990961 0.04386778 0.24253241]
 [0.58362154 0.19365921 0.73131058 0.54673692]
 [0.34738314 0.4634587  0.36476761 0.48515853]]


In [87]:
M.sum(axis=0)   # Сумма элементов двумерного массива по столбцам

array([1.13121019, 1.37702752, 1.13994597, 1.27442786])

In [88]:
M.sum(axis=1)   # Сумма элементов двумерного массива по строкам

array([1.20651531, 2.05532825, 1.66076798])

In [89]:
M.sum()         # Сумма всех элементов двумерного массива

4.922611543412104

<h2 style="text-align:center; margin-top:40px; margin-bottom:30px">Сравнения, маски и булева логика</h2>

<div style="text-align:center"><img src="comparison.png" width="600"></div>

In [90]:
x = np.array([1, 2, 3, 4, 5])   # Создадим одномерный массив

In [91]:
x > 3   # Проверим наличие элементов массива, удовлетворяющих условию

array([False, False, False,  True,  True])

In [92]:
x = np.random.randint(10, size=(3, 4))  # Создадим случайный двумерный массив
x

array([[3, 8, 8, 4],
       [6, 8, 4, 0],
       [5, 4, 8, 8]])

In [93]:
x >= 6   # Проверим наличие элементов массива, удовлетворяющих условию

array([[False,  True,  True, False],
       [ True,  True, False, False],
       [False, False,  True,  True]])

<div style="text-indent:30px; text-align:justify; margin-top:20px">Для подсчета количества элементов <strong>True</strong> в булевом массиве удобно использовать функцию <strong>np.count_nonzero()</strong>: </div>

In [94]:
np.count_nonzero(x >= 6)

6

In [95]:
# Сколько значений, больших или равных 6, содержится в каждой строке?
np.sum(x >= 6, axis=1)

array([2, 2, 2])

<div style="text-indent:30px; text-align:justify; margin-top:20px">Если вам необходимо быстро проверить, существует ли хоть одно истинное значение, или все ли значения истинны, можно воспользоваться функциями <strong>np.any()</strong> и <strong>np.all()</strong>: </div>

In [96]:
# Имеются ли в массиве какие-либо значения, превышающие 8?
np.any(x > 8)

False

In [97]:
# Все ли значения в каждой строке меньше 8?
np.all(x < 8, axis=1)

array([False, False, False])

<div style="text-indent:30px; text-align:justify; margin-top:20px">Чтобы выбрать нужные значения из массива, достаточно просто проиндексировать исходный массив <strong>x</strong> по этому булеву массиву. Такое действие носит название операции наложения маски или <strong>маскирования</strong>: </div>

In [98]:
x

array([[3, 8, 8, 4],
       [6, 8, 4, 0],
       [5, 4, 8, 8]])

In [99]:
x < 5

array([[ True, False, False,  True],
       [False, False,  True,  True],
       [False,  True, False, False]])

In [100]:
x[x < 5]  # Наложение маски

array([3, 4, 4, 0, 4])

In [101]:
# При создании булева выражения с заданным массивом следует использовать операторы & и |, а не операции and или or:
x = np.arange(10)
x[(x > 4) & (x < 8)]

array([5, 6, 7])